### ISSUE TITLE
MFA2.0效果和1.0相比有没有提升

### ISSUE THREAD

**Issue by kslz** [jerryuhoo/VTuberTalk#13]
如题

**Comment by jerryuhoo** [comment]
我用了最新的2.0，我记得2.0和1.0有个差别就是默认生成的TextGrid里，2.0把sp和sil直接变成空格了，当然也可以加参数来调整，不过我记得paddlespeech应该做过兼容的。至于训练效果是否有提升这个我不清楚，没看过他代码的改动。

**Comment by kslz** [comment]
> 我用了最新的2.0，我记得2.0和1.0有个差别就是默认生成的TextGrid里，2.0把sp和sil直接变成空格了，当然也可以加参数来调整，参考[这里](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/377)。不过我记得paddlespeech应该做过兼容的。至于训练效果是否有提升这个我不清楚，没看过他代码的改动。

感谢
