### ISSUE TITLE
请问界面中可以选择的那个参考音频是什么作用

### ISSUE THREAD

**Issue by kslz** [jerryuhoo/VTuberTalk#15]
试了一下 好像没听出变化来

**Comment by jerryuhoo** [comment]
https://github.com/jerryuhoo/VTuberTalk/blob/4b5c9f6d91b33c4725ce103f69f6b07915b9f5d0/run_train.sh#L8

GST训练的时候用，GST的作用是让输出的音频的语气语调更加像参考音频一点，但是实际上效果也一般，默认设置为False，就没有作用。前几天更新了一下，目前选择普通fastspeech模型的时候会隐藏掉这个参考音频的按钮。

**Comment by kslz** [comment]
感谢解答
