### ISSUE TITLE
一个程序正在使用此文件,进程无法访问

### ISSUE THREAD

**Issue by Liovfan** [jerryuhoo/VTuberTalk#2]
(VTuberTalk) C:\works\2022\MockingBird\VTuberTalk-2.0\VTuberTalk-2.0>python tools/revise_text.py --path C:\works\2022\MockingBird\VTuberTalk-2.0\VTuberTalk-2.0\data\wav\1\split\
Traceback (most recent call last):
  File "tools/revise_text.py", line 53, in <module>
    process(files, args.path)
  File "tools/revise_text.py", line 33, in process
    move(path, file, outdir)
  File "tools/revise_text.py", line 6, in move
    os.replace(os.path.join(root_path, file_name), os.path.join(output_path, file_name))
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\works\\2022\\MockingBird\\VTuberTalk-2.0\\VTuberTalk-2.0\\data\\wav\\1\\split\\01_00.txt' -> 'C:\\works\\2022\\MockingBird\\VTuberTalk-2.0\\VTuberTalk-2.0\\data\\wav\\1\\split\\../unrecognized\\01_00.txt'

运行时经常出现“另一个程序正在使用此文件，进程无法访问。”，如何解决

**Comment by jerryuhoo** [comment]
在linux里没有问题，但是在windows里可能权限不够，试试用管理员身份运行终端？

**Comment by Liovfan** [comment]
> 在linux里没有问题，但是在windows里可能权限不够，试试用管理员身份运行终端？因为这一步操作涉及到覆盖原来的txt文件，如果你打开原来的txt文件的话可能无法覆盖。

使用管理员身份也不行

**Comment by jerryuhoo** [comment]
感谢提出这个问题，原因是没有close file，已在最新的commit中修复
