### ISSUE TITLE
MFA train failed

### ISSUE THREAD

**Issue by leon2milan** [jerryuhoo/VTuberTalk#9]
MFA versiong is `2.0.0rc3`. 
I set Tshinghua channel to conda. And installed by `conda create -n aligner  montreal-forced-aligner`.
I ran step 9, got  `No such file or directory: '/home/XXX/Documents/MFA/split_train_acoustic_model/monophone/0.pinyin_eng.0.acc'`.

I don't know how to deal with this.

**Comment by jerryuhoo** [comment]
不知道你运行的是run_preprocess.sh还是单独用了MFA的命令，确保dict的路径和命令行里的路径一样

**Comment by jerryuhoo** [comment]
那可能是MFA的bug，我没试过这个版本的，我用的是2.0.0b10版本，你可以试试看

**Comment by leon2milan** [comment]
@jerryuhoo 错误原因是由于：MFA 需要openfst  我之前自己安装了一个低版本， 而conda 会安装最新的， 需要C++ 17.       
conda 安装MFA 需要一系列工具 如 openfst kaldi等等。 简单的做法在一开始创建虚拟环境的时候 加上`-c conda-forge montreal-forced-aligner`.   或许需要在文档中注明一下。  
由于openfst的原因， MFA需要gcc g++ 版本大于 7（没有尝试本地版本为4.8时，conda 安装最新openfst 是否能成功运行）  
我是如下安装的：  
```
conda create -n aligner -c conda-forge openblas kaldi sox python=3.8 openfst pynini ngram baumwelch  
pip install montreal-forced-aligner==2.0.0b10  
```  
我没有尝试MFA最新版本`2.0.0rc3`是否能成功运行。
